# Generated by Django 5.1.3 on 2024-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('1', 'verduras'), ('2', 'frutas'), ('3', 'farináceos'), ('4', 'lácteos'), ('5', 'grasas')], default='1', max_length=5)),
                ('racion', models.IntegerField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
