# Generated by Django 5.1.3 on 2024-11-18 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date(2024, 11, 18))),
                ('observaciones', models.TextField(blank=True, max_length=300, null=True)),
                ('ingredientes', models.ManyToManyField(related_name='recetas', to='ingredientes.ingredientes')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
