# Generated by Django 5.1.3 on 2024-11-20 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetas',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recetas',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 11, 20)),
        ),
    ]
