# Generated by Django 5.1.3 on 2024-11-21 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_recetas_options_recetas_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 11, 21)),
        ),
    ]
