# Generated by Django 5.1.3 on 2024-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_recetas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
