# Generated by Django 5.1.3 on 2024-11-22 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_recetas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 11, 22)),
        ),
    ]
