# Generated by Django 5.1.3 on 2024-11-22 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0003_alter_dietas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietas',
            name='activada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dietas',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 11, 22)),
        ),
    ]
