# Generated by Django 5.1.3 on 2024-11-25 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0004_dietas_activada_alter_dietas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietas',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 11, 25)),
        ),
    ]
