# Generated by Django 5.1.3 on 2024-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_alter_platos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
