# Generated by Django 5.1.3 on 2024-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0003_alter_platos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
