# Generated by Django 5.1.3 on 2024-11-18 09:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dietas', '0001_initial'),
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 11, 18, 10, 23, 55, 111560))),
                ('dieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comidas', to='dietas.dietas')),
                ('platos', models.ManyToManyField(related_name='comidas', to='platos.platos')),
            ],
        ),
    ]
