# Generated by Django 5.1.3 on 2024-11-22 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0005_alter_comidas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidas',
            name='momento',
            field=models.CharField(choices=[(1, 'desayuno'), (2, 'media mañana'), (3, 'almuerzo'), (4, 'merienda'), (5, 'cena'), (6, 'antes de dormir')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comidas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 12, 15, 27, 442591)),
        ),
    ]
