# Generated by Django 5.1.3 on 2024-11-22 11:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0007_alter_comidas_dieta_alter_comidas_fecha'),
        ('dietas', '0004_dietas_activada_alter_dietas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='dieta',
            field=models.ForeignKey(blank=True, limit_choices_to={'activada': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comidas', to='dietas.dietas'),
        ),
        migrations.AlterField(
            model_name='comidas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 12, 19, 32, 147006)),
        ),
    ]
