# Generated by Django 5.1.3 on 2024-11-22 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0008_alter_comidas_dieta_alter_comidas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 12, 30, 51, 900288)),
        ),
        migrations.AlterField(
            model_name='comidas',
            name='momento',
            field=models.IntegerField(choices=[(1, 'desayuno'), (2, 'media mañana'), (3, 'almuerzo'), (4, 'merienda'), (5, 'cena'), (6, 'antes de dormir')], max_length=10),
        ),
    ]
