# Generated by Django 5.1.3 on 2024-11-22 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0009_alter_comidas_fecha_alter_comidas_momento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 11, 22, 12, 44, 6, 727835)),
        ),
    ]
