# Generated by Django 5.1.3 on 2024-12-09 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0012_alter_comidas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 20, 36, 56, 751469)),
        ),
    ]
